name: burst2safe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - pip
  - gdal
  - shapely>=2.0.6
  - numpy
  - lxml
  - tifffile>=2022.04.22
  - asf_search
  - dateparser!=1.1.0
  - aiohttp
  # For packaging, and testing
  - pytest
  - pytest-cov
  - pytest-dependency
  - pip:
    - -r requirements-static.txt
