name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  call-pytest-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: forrestfwilliams/burst2safe/.github/workflows/reusable-pytest.yml
    with:
      local_package_name: burst2safe
      additional_args: -m integration
