on:
  workflow_call:
    inputs:
      local_package_name:
        required: true
        type: string
      python_versions:
        required: false
        default: >-
          ["3.10", "3.11", "3.12"]
        description: JSON string containing the list of python versions to test
        type: string
      additional_args:
        required: false
        type: string
        description: Additional arguments to pass to pytest as string
        default: ""

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ${{ fromJson(inputs.python_versions) }}

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python_version }}

      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps .
          pytest --cov=${{ inputs.local_package_name }} ${{ inputs.pytest_args }}
